apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nephio
    app.kubernetes.io/part-of: nephio
    app.kubernetes.io/version: tbd
  name: nephio-controller-approval-role
rules:
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions
  - packagerevisions/status
  - packagerevisions/approval
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - packagevariants
  - packagevariants/status
  verbs:
  - get
  - list
  - watch
