apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-rootsync
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: rootsync
    repo: nephio-test-packages
    revision: v3
  downstream:
    package: example-rootsync
    repo: mgmt-staging
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
